### PR TITLE
adds UMD (Universal Module Definition) support

### PR DESCRIPTION
**Pull request by pirelenito**
In the process of adding UMD module support, it was required that the compilation level of the closure compiler to be reduced to “SIMPLE_OPTIMIZATIONS”.

The problem with “ADVANCED_OPTIMIZATIONS” is its “more aggressive renaming”, also renames the global variables such as AMD’s and CommonJS’s inside the minified file, breaking the UMD code.

for more information see: https://developers.google.com/closure/compiler/docs/compilation_levels

Thanks for the great project! My motivation for this change is allowing me to more easily use mdEdit in an environment such as [Atom Electron](http://electron.atom.io/).

A pretty good benefit is also allowing you to make this a NPM package.

### CODE REVIEW

**Comment by jbt** [comment]
Great! I've been wanting to add UMD but I don't really use it myself elsewhere so I wasn't sure exactly what needed doing.

I'm sure there's a way to make it play nicely with ADVANCED_OPTIMIZATIONS if necessary, probably just a matter of changing a few cases of `foo.bar` to `foo['bar']` in the UMD wrapper. I'll take a quick look and see what I can come up with.

**Comment by jbt** [comment]
Hi @pirelenito I've had a little play with this over on #5 to try and make it work nicely with ADVANCED_OPTIMIZATIONS - do you want to give that a quick look and see if it works properly with whatever use-case you had for this? (I don't know enough about the different UMD use-cases so I may have broken it...)

**Comment by pirelenito** [comment]
Hi @jbt. I've just looked at it, tested on my project and it worked flawlessly :smile: 

I've also reviewed the changes and compiled code, and everything seems OK.

Thanks a lot for taking the time to review my pull request.

**Comment by jbt** [comment]
Awesome, great to hear! I'll get that merged into master then!

**Pull request merged**
